import esbuild from "esbuild";
import process from "process";
import { writeFileSync } from "fs";
import builtins from "builtin-modules";

const banner =
`#!/usr/bin/env node
/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this project
*/
`;

const prod = (process.argv[2] === "production");

const buildConfig = {
	banner: {
		js: banner,
	},
	entryPoints: ["src/index.ts"],
	bundle: true,
	format: "cjs",
	target: "node16",
	platform: "node",
	logLevel: "info",
	sourcemap: true,
	treeShaking: true,
	outdir: "dist",
	mainFields: ["module", "main"],
	tsconfig: "tsconfig.json",
	minify: true,
	metafile: true,
	external: [
		...builtins,
	],
};

if (prod) {
	const buildResult = await esbuild.build(buildConfig);
	writeFileSync("./dist/meta.json", JSON.stringify(buildResult.metafile));
} else {
	const context = await esbuild.context(buildConfig);
	await context.watch();
}
